---
- name: Download and install the ws package
  hosts: ws
  become: True
  ignore_errors: 1
  gather_facts: yes
  tasks:
    - name: Download the ws package
      get_url:
        url: "https://github.com/kserge2001/resume/archive/refs/heads/main.zip"
        dest: "/tmp/main.zip"
        
- name: Delete file
  file:
  path: /tmp/main.zip
  state: absent