---
- name: Download and install the ws package
  hosts: ws
  become: True
  ignore_errors: 1
  gather_facts: yes
  tasks:
    - name: Download the ws package
      get_url:
        url: "{{LINK_URL}}"
        dest: "{{DESTINATION}}"
        
- name: Delete file
  file:
  path: /tmp/main.zip
  state: absent
